ANNETY/Annety/Annety/Controllers/ColorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Annety;

namespace Annety.Controllers
{
    public class ColorsController : Controller
    {
        private AnnetyEntities db = new AnnetyEntities();

        // GET: Colors
        public ActionResult Index()
        {
            return View(db.Colors.ToList());
        }

        // GET: Colors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colors colors = db.Colors.Find(id);
            if (colors == null)
            {
                return HttpNotFound();
            }
            return View(colors);
        }

        // GET: Colors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Colors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodeColor,ColorName")] Colors colors)
        {
            if (ModelState.IsValid)
            {
                db.Colors.Add(colors);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(colors);
        }

        // GET: Colors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colors colors = db.Colors.Find(id);
            if (colors == null)
            {
                return HttpNotFound();
            }
            return View(colors);
        }

        // POST: Colors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CodeColor,ColorName")] Colors colors)
        {
            if (ModelState.IsValid)
            {
                db.Entry(colors).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(colors);
        }

        // GET: Colors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colors colors = db.Colors.Find(id);
            if (colors == null)
            {
                return HttpNotFound();
            }
            return View(colors);
        }

        // POST: Colors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Colors colors = db.Colors.Find(id);
            db.Colors.Remove(colors);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ANNETY/Annety/Annety/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Annety;
using System.IO;

namespace Annety.Controllers
{
    public class ProductsController : Controller
    {
        private AnnetyEntities db = new AnnetyEntities();

        // GET: Products
        public ActionResult Index()
        {
            var product = db.Product.Include(p => p.Categories);
            return View(product.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CategoryCode = new SelectList(db.Categories, "CategoryCode", "LongName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductKey,Barcode,Image,ImagePath,Desc,CategoryCode,Price,SearchWords")] Product product)
        {
            if (ModelState.IsValid)
            {
                var ext = Path.GetExtension(product.Image.FileName);
                string imageName = product.Barcode.ToString();
                string myimage = imageName + ext;
                product.ImagePath = Path.Combine(Server.MapPath("~/ProductImages"), myimage);
                product.Image.SaveAs(product.ImagePath);
                product.ChangeDate = DateTime.Now;
                db.Product.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryCode = new SelectList(db.Categories, "CategoryCode", "LongName", product.CategoryCode);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryCode = new SelectList(db.Categories, "CategoryCode", "Desc", product.CategoryCode);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductKey,Barcode,ImagePath,Desc,CategoryCode,Price,SearchWords")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryCode = new SelectList(db.Categories, "CategoryCode", "Desc", product.CategoryCode);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Product.Find(id);
            db.Product.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Item(int? id)
        {
            int mone = 0;
            Product p = db.Product.SingleOrDefault(i=>i.ProductKey == id);

            //add to session
            if (Session["kk"] == null)
                Session["kk"] = new Stack<Product>();
            Stack<Product> f = (Stack<Product>)Session["kk"];
            foreach (var x in f)
            {
                if (p.ProductKey == x.ProductKey)
                    mone = 1;
            }
            if(mone==0)
            f.Push(p);
            Session["kk"] = f;
           
            return View(p);
        }

        public ActionResult WatchList( )
        {
            //get from to session
            if (Session["kk"] != null)
            {
                List<Product> l = ((Stack<Product>)Session["kk"]).ToList();
                return View(l.Take(10));
            }
            return View( );
        }

    }
}

ANNETY/Annety/Annety/Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Annety;

namespace Annety.Controllers
{
    public class StocksController : Controller
    {
        private AnnetyEntities db = new AnnetyEntities();

        // GET: Stocks
        public ActionResult Index()
        {
            var stocks = db.Stocks.Include(s => s.Colors).Include(s => s.Product).Include(s => s.ProductSize);
            return View(stocks.ToList());
        }

        // GET: Stocks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stocks stocks = db.Stocks.Find(id);
            if (stocks == null)
            {
                return HttpNotFound();
            }
            return View(stocks);
        }

        // GET: Stocks/Create
        public ActionResult Create()
        {
            ViewBag.ProdColorKey = new SelectList(db.Colors, "CodeColor", "ColorName");
            ViewBag.ProductKey = new SelectList(db.Product, "ProductKey", "Barcode");
            ViewBag.CodeSize = new SelectList(db.ProductSize, "CodeSize", "SizeDesc");
            return View();
        }

        // POST: Stocks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StockCode,ProductKey,ProdColorKey,UnitsInStocks,CodeSize")] Stocks stocks)
        {
            if (ModelState.IsValid)
            {
                db.Stocks.Add(stocks);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProdColorKey = new SelectList(db.Colors, "CodeColor", "ColorName", stocks.ProdColorKey);
            ViewBag.ProductKey = new SelectList(db.Product, "ProductKey", "Barcode", stocks.ProductKey);
            ViewBag.CodeSize = new SelectList(db.ProductSize, "CodeSize", "SizeDesc", stocks.CodeSize);
            return View(stocks);
        }

        // GET: Stocks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stocks stocks = db.Stocks.Find(id);
            if (stocks == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProdColorKey = new SelectList(db.Colors, "CodeColor", "ColorName", stocks.ProdColorKey);
            ViewBag.ProductKey = new SelectList(db.Product, "ProductKey", "Barcode", stocks.ProductKey);
            ViewBag.CodeSize = new SelectList(db.ProductSize, "CodeSize", "SizeDesc", stocks.CodeSize);
            return View(stocks);
        }

        // POST: Stocks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StockCode,ProductKey,ProdColorKey,UnitsInStocks,CodeSize")] Stocks stocks)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stocks).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProdColorKey = new SelectList(db.Colors, "CodeColor", "ColorName", stocks.ProdColorKey);
            ViewBag.ProductKey = new SelectList(db.Product, "ProductKey", "Barcode", stocks.ProductKey);
            ViewBag.CodeSize = new SelectList(db.ProductSize, "CodeSize", "SizeDesc", stocks.CodeSize);
            return View(stocks);
        }

        // GET: Stocks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stocks stocks = db.Stocks.Find(id);
            if (stocks == null)
            {
                return HttpNotFound();
            }
            return View(stocks);
        }

        // POST: Stocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Stocks stocks = db.Stocks.Find(id);
            db.Stocks.Remove(stocks);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ANNETY/Annety/Annety/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Annety;

namespace Annety.Controllers
{
    public class UsersController : Controller
    {
        private AnnetyEntities db = new AnnetyEntities();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Code,UserName,Email,Password,Address,Phone")] Users users)
        {
            if (ModelState.IsValid)
            {   //users.Password
                users.Password = AccountController.HashPass(users.Password);
                db.Users.Add(users);
                db.SaveChanges();
                return RedirectToAction("Index");
            }   

            return View(users);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Code,UserName,Email,Password,Address,Phone")] Users users)
        {
            if (ModelState.IsValid)
            {
                db.Entry(users).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(users);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Users users = db.Users.Find(id);
            db.Users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ANNETY/Annety/Annety/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
@*<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>*@

<body style="background:url(../Images/Picture2.jpg); background-size:100%;background-repeat:no-repeat;background-attachment:scroll">

</body>

@*<p>Use this area to provide additional information.</p>*@

ANNETY/Annety/Annety/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
   Annety<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ANNETY/Annety/Annety/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<style>
     #cf1 img {
            position:absolute;
            left:0;
            -webkit-transition: opacity 1s ease-in-out;
            -moz-transition: opacity 1s ease-in-out;
            -o-transition: opacity 1s ease-in-out;
            transition: opacity 1s ease-in-out;
        }

        #cf1 img.top:hover {
            opacity:0;
        }


</style>
<div class="HomePage">
    <div class="row" >
        <div class="cf1" id="cf1">
            <a href='../SearchResult/BoyOrGirl?CategoryCode=0'>

                <img class="bottom" src="~/Images/girls color.jpg" style="width:570px; height:500px; margin:auto;left:200px;" />
                <img class="top" src="~/Images/girls BW.jpg" style="width:570px; height:500px; margin:auto;position:absolute; left:200px;" />
            </a>
        </div>
       
           
        </div>
    <div class="cf1" id="cf1">

                <a  href='../SearchResult/BoyOrGirl?CategoryCode=1' >
                    <img class="bottom" src="~/Images/boys color.jpg" style="width:570px; height:500px;left:770px;margin:auto" />
                    <img class="top" src="~/Images/boys BW.jpg" style="width:570px; height:500px;position:absolute; left:770px;" />
                </a>
   </div>
            
        @*</div>
    </div>*@
    @*<a href="C:/Users/DANA/Desktop/Annety/ANNETY/Annety/Annety/web/index.html">Pay Now</a>*@
    @*<a class="PayNowBottun" href="~/Views/Payment/index.html">Pay Now</a>*@
  
   @*<div class="row">
       <div>תמונה 1</div>
       <div>תמונה 2</div>
       <div>תמונה 3</div>
       <div>תמונה 4</div>
       <div>תמונה 5</div>
       <div>תמונה 6</div>
   </div>*@
</div>

ANNETY/Annety/Annety/Views/Home/Manage.cshtml
@{
    ViewBag.Title = "Manage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page1">
    <h2>Manage</h2>

    <div>
        <div class="row" style="margin-left:20px">
            <h4>Categories</h4>
            <ol class="nav navbar-nav row">
                <li class="co-md-7">@Html.ActionLink("Add New Category", "Create", "Categories")</li>
                <li class="col-md-7">@Html.ActionLink("All Categories", "Index", "Categories")</li>
            </ol>
        </div>
        <div class="row">
            <h4>Colors</h4>
            <ol class="nav navbar-nav row">
                <li class="co-md-7">@Html.ActionLink("Add New Color", "Create", "Colors")</li>
                <li class="col-md-7">@Html.ActionLink("All Colors", "Index", "Colors")</li>
            </ol>
        </div>
        <div class="row">
            <h4>Products</h4>
            <ol class="nav navbar-nav row">
                <li class="co-md-7">@Html.ActionLink("Add New Product", "Create", "Products")</li>
                <li class="col-md-7">@Html.ActionLink("All Products", "Index", "Products")</li>
            </ol>
        </div>
        <div class="row">
            <h4>Sizes</h4>
            <ol class="nav navbar-nav row">
                <li class="co-md-7">@Html.ActionLink("Add New Size", "Create", "ProductSizes")</li>
                <li class="col-md-7">@Html.ActionLink("All Sizes", "Index", "ProductSizes")</li>
            </ol>
        </div>
        <div class="row">
            <h4>Stock</h4>
            <ol class="nav navbar-nav row">
                <li class="co-md-7">@Html.ActionLink("Add Products To Stock", "Create", "Stocks")</li>
                <li class="col-md-7">@Html.ActionLink("All In Stocks", "Index", "Stocks")</li>
            </ol>
        </div>
        <div class="row">
            <h4>Users</h4>
            <ol class="nav navbar-nav row">
                <li class="col-md-7">@Html.ActionLink("All Users", "Index", "Users")</li>
            </ol>
        </div>
        <div class="row">
            <h4>UsersOrders</h4>
            <ol class="nav navbar-nav row">
                <li class="co-md-7">@Html.ActionLink("Create New Order", "Create", "UsersOrders")</li>
                <li class="col-md-7">@Html.ActionLink("All The Orders", "Index", "UsersOrders")</li>
            </ol>
        </div>
    </div>
</div>